ppo:
  env: MountainCar-ShapedReward-v0
  agent_kwargs:
    activation: swish
  num_envs: 20
  num_steps: 200
  num_epochs: 1
  num_minibatches: 10
  learning_rate: 0.0001
  max_grad_norm: 1.0
  total_timesteps: 10_000_000
  eval_freq: 100000
  gamma: 1.0
  gae_lambda: 1.0
  clip_eps: 10.0
  ent_coef: 0.0
  vf_coef: 0.04